export enum AuthorizeActionTypes {
  AUTHORIZE_USER = 'AUTHORIZE_USER',
  AUTHORIZE_USER_SUCCESS = 'AUTHORIZE_USER_SUCCESS',
  AUTHORIZE_USER_ERROR = 'AUTHORIZE_USER_ERROR',
}

export enum RegisterActionTypes {
  REGISTER_USER = 'REGISTER_USER',
  REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS',
  REGISTER_USER_ERROR = 'REGISTER_USER_ERROR',
}

export enum GetCurrentUserActionTypes {
  GET_CURRENT_USER = 'GET_CURRENT_USER',
  GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS',
  GET_CURRENT_USER_ERROR = 'GET_CURRENT_USER_ERROR',
}

export enum EditUserActionTypes {
  EDIT_USER_DATA = 'EDIT_USER_DATA',
  EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS',
  EDIT_USER_ERROR = 'EDIT_USER_ERROR',
}

export enum ConfirmUserActionTypes {
  CONFIRM_USER = 'CONFIRM_USER',
  CONFIRM_USER_SUCCESS = 'CONFIRM_USER_SUCCESS',
  CONFIRM_USER_ERROR = 'CONFIRM_USER_ERROR',
}

export enum LogoutActionType {
  LOGOUT_USER = 'LOGOUT_USER',
}
